# Generated by Django 3.1.3 on 2020-11-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discharge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='admitDate',
            field=models.DateField(null=True),
        ),
    ]
