# Generated by Django 3.1.3 on 2020-11-10 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(max_length=40)),
                ('doctorName', models.CharField(max_length=40)),
                ('appointmentDate', models.DateField(auto_now=True)),
                ('doctorId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctorID', to=settings.AUTH_USER_MODEL)),
                ('patientId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patientID', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
