# Generated by Django 3.1.3 on 2020-11-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'confirmed'), ('Pending', 'pending')], default='Pending', max_length=20),
        ),
    ]
