# Generated by Django 3.1.3 on 2020-11-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'confirmed'), ('Pending', 'pending')], default='Pending', editable=False, max_length=20),
        ),
    ]
