# Generated by Django 3.1.3 on 2020-11-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20201110_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'confirmed'), ('Pending', 'pending'), ('Visited', 'visited')], default='Pending', max_length=20),
        ),
    ]
