# Generated by Django 3.1.3 on 2020-11-29 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0007_auto_20201111_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctorID', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patientId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientID', to=settings.AUTH_USER_MODEL),
        ),
    ]
