# Generated by Django 3.1.3 on 2020-11-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20201118_0718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='count',
            new_name='scount',
        ),
    ]
