# Generated by Django 3.1.3 on 2020-11-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='history',
            name='doctorId',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='history',
            name='hospitalName',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='history',
            name='treatment',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
