# Generated by Django 3.1.3 on 2020-11-16 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalName', models.CharField(max_length=350)),
                ('treatment', models.CharField(max_length=250)),
                ('date', models.DateTimeField()),
                ('doctorId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctorId', to=settings.AUTH_USER_MODEL)),
                ('patientId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patientId', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
