# Generated by Django 3.1.3 on 2020-11-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='count',
            new_name='dcount',
        ),
    ]
