# Generated by Django 3.1.3 on 2020-11-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20201109_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='hospital',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
